raumplanung-master/planning/urls.py
from django.urls import path

from . import views

app_name = 'planning'
urlpatterns = [
    path('', views.index, name='index'),
    path('all_bookings', views.all_bookings, name='all_bookings'),
    path('space/<int:space_id>/', views.space, name='space'),
    path('space/<int:space_id>/<int:date_id>/<int:slot_id>/book/', views.book_space, name='book_space'),

]

raumplanung-master/rooms/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth import views as auth_views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls')),
    path('', include('planning.urls')),
]

raumplanung-master/planning/models.py
from django.db import models
from django.contrib.auth.models import User
from datetime import date as pydate, time

# Anlegen der Models zur Datenhaltung
# Entgegen der ursprünglichen Planung werden Foreign Keys zur Referenzierung auf andere Objekte verwendet
# um nicht manuell über die Felder die zugehörigen Objekte suchen zu müssen
# from planning.models import User, Space, Calendar, Timeslot, BookingTime, BookedRoom, Booking


# User Model
# class User(models.Model):
#    username = models.CharField(max_length=50)
#    password = models.CharField(max_length=50)
#    email = models.CharField(max_length=50)
#    admin = models.BooleanField()


# Spaces Model
class Space(models.Model):
    title = models.CharField(max_length=50)
    size = models.IntegerField()
    equipment = models.CharField(max_length=300)

    def __str__(self):
        return '{}'.format(self.title)


# Calendar Model
class Calendar(models.Model):
    date = models.DateField()

    def __str__(self):
        return '{}'.format(pydate.strftime(self.date, '%d.%m.%Y'))


# Timeslot Model
class Timeslot(models.Model):
    start = models.TimeField()
    end = models.TimeField()
    duration = models.DurationField()

    def __str__(self):
        return '{} bis {}'.format(time.strftime(self.start, '%H:%M'), time.strftime(self.end, '%H:%M'))


# BookingTime Model
# class BookingTime(models.Model):
#    date = models.ForeignKey(Calendar, models.CASCADE)  # Referenz auf das Kalenderdatum
#    slot = models.ForeignKey(Timeslot, models.CASCADE)  # Referent auf den Timeslot


# BookedRoom Model
class Booking(models.Model):
    space = models.ForeignKey(Space, models.CASCADE, default=0)  # Referenz auf den betroffenen Raum
    # bookingTime = models.ForeignKey(BookingTime, models.CASCADE)
    date = models.ForeignKey(Calendar, models.CASCADE, default=0)  # Referenz auf das Kalenderdatum
    slot = models.ForeignKey(Timeslot, models.CASCADE, default=0)  # Referent auf den Timeslot
    user = models.ForeignKey(User, models.CASCADE, default=0)  # Referenz auf den User der die Buchung getätigt hat.

    def __str__(self):
        return '{}: {}, {} ({})'.format(self.space, self.date, self.slot, self.user)


# Booking Model
# class Booking(models.Model):
#    user = models.ForeignKey(User, models.CASCADE)  # Referenz auf den User der die Buchung getätigt hat.
#    bookedRoom = models.ForeignKey(BookedRoom, models.CASCADE)  # Referenz auf die

raumplanung-master/planning/views.py
from django.shortcuts import render, get_object_or_404
from django.http import Http404
from django.http import HttpResponse
from .models import Space, Calendar, Timeslot, Booking
from django.contrib.auth.models import User
from datetime import date
from django.contrib.auth.decorators import login_required


@login_required
def index(request):
    spaces = Space.objects.order_by('title')
    context = {
        'spaces' : spaces
    }
    return render(request, 'planning/index.html', context)


@login_required
def space(request, space_id):
    space = get_object_or_404(Space, pk=space_id)
    dates = Calendar.objects.all().filter(date__gte = date.today()).order_by('date')
    timeslots = Timeslot.objects.order_by('start')

    details = []

    for calendarDate in dates:
        for timeslot in timeslots:
            details.append({
                'date': calendarDate,
                'timeslot': timeslot,
                'booked': len(Booking.objects.all().filter(space=space, date=calendarDate, slot=timeslot)) > 0
            })


    context = {
        'space': space,
        'details': details
    }
    return render(request, 'planning/space.html', context)


@login_required
def book_space(request, space_id, date_id, slot_id):
    space = get_object_or_404(Space, pk=space_id)
    calendarDate = get_object_or_404(Calendar, pk=date_id)
    timeslot = get_object_or_404(Timeslot, pk=slot_id)
    user = request.user
    show_form = True
    existing = Booking.objects.all().filter(user=user, date__date__gte=date.today()).first()
    message = ''

    if request.method == 'POST': # Hier wird geprüft ob das Formular abgesendet wurde.
        show_form = False
        if request.POST['choice'] == 'confirm':
            if len(Booking.objects.all().filter(space=space, date=calendarDate, slot=timeslot)) > 0:
                message = 'Der Raum ist bereits gebucht'
            else:
                if existing is not None:
                    existing.delete()
                booking = Booking(space=space, slot=timeslot, date=calendarDate, user=user)
                booking.save()
                message = 'Raum gebucht!'
        else:
            message = 'Der Raum wurde nicht gebucht'


    context = {
        'message': message,
        'space': space,
        'date': calendarDate,
        'slot': timeslot,
        'existing': existing,
        'show_form': show_form,
    }

    return render(request, 'planning/booking.html', context)


@login_required
def all_bookings(request):
    bookings = Booking.objects.all().filter(date__date__gte=date.today()).order_by('date', 'slot')

    context = {
        'bookings': bookings
    }
    return render(request, 'planning/all_bookings.html', context)

raumplanung-master/planning/templates/planning/all_bookings.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Buchungsübersicht</title>
</head>
<body>
<h1>Alle Buchungen</h1>

{% for booking in bookings %}
    <br>
    <div>
        <div>
            <span>{{ booking }} </span>
        </div>
        <div>
            <span>Stornieren</span>
        </div>
    </div>
    <hr>
{% endfor %}

<span><a href="{% url 'planning:index' %}">Zur Startseite</a></span>

</body>
</html>

raumplanung-master/planning/templates/planning/booking.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Raumbuchung</title>
</head>
<body>
<h1>Raumbuchung</h1>
<p>{{ message }}</p>

{% if show_form %}
    <p>Möchten Sie den gewählten Raum wirklich buchen? ({{ space.title }}, {{ date.date|date:"d.m.Y" }}, {{ slot.start|time:"H:i" }} - {{ slot.end|time:"H:i" }})</p>
    {% if existing is not None %}
        <p>Ihre bestehende Buchung wird gelöscht ({{ existing.space.title }}, {{ existing.date.date|date:"d.m.Y" }}, {{ existing.slot.start|time:"H:i" }} - {{ existing.slot.end|time:"H:i" }})</p>
    {% endif %}
<form action="{% url 'planning:book_space' space.id date.id slot.id %}" method="post">
{% csrf_token %}
<fieldset>
    <input type="radio" id="confirm" name="choice" value="confirm">
    <label for="confirm"> Ja </label>
    <input type="radio" id="dismiss" name="choice" value="dismiss">
    <label for="dismiss"> Nein </label>
  </fieldset>
<input type="submit" value="Bestätigen">
</form>
{% else %}
    <a href="{% url 'planning:index' %}">Zurück zur Startseite</a>
{% endif %}


</body>
</html>

raumplanung-master/planning/templates/planning/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Übersicht</title>
</head>
<body>
<h1>Übersicht (Räume)</h1>

{% if spaces %}
    <ul>
    {% for space in spaces %}
        <li><a href="{% url 'planning:space' space.id %}">{{ space.title }}</a></li>
    {% endfor %}
    </ul>
{% else %}
    <p>Keine Räume angelegt!</p>
{% endif %}

<span><a href="{% url 'planning:all_bookings' %}">Zur Buchungsübersicht</a></span>


</body>
</html>

raumplanung-master/planning/templates/planning/space.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Raum (Detailansicht)</title>
</head>
<body>
<h1>{{ space.title }} (Detailansicht)</h1>
<p>Ausstattung: {{ space.equipment }}</p>
<p>Plätze: {{ space.size }}</p>

{% for detail in details %}
    <br>
    <div>
        <div>
            <span>{{ detail.date.date|date:"d.m.Y" }}</span> <span>Start: {{ detail.timeslot.start|time:"H:i" }} Ende: {{ detail.timeslot.end|time:"H:i" }}</span>
        </div>
        <div>
            {% if detail.booked %}
                <span>Belegt</span>
            {% else %}
                <span>Frei</span><span> <a href="{% url 'planning:book_space' space.id detail.date.id detail.timeslot.id%}">Jetzt buchen</a></span>
            {% endif %}
        </div>
    </div>
    <hr>
{% endfor %}

</body>
</html>